### ISSUE TITLE
Fidesops 1.4 Release Checklist

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fidesops#372]
- [x] Quickstart verified working and up-to-date? 
  - (Verified by Dawn - a future improvement, maybe we put some more mandatory pauses in it.  You can fly through it and submit an erasure and then an access request back to back. The erasure hasn't processed yet, so the follow-up access request returns data and makes it look like the erasure didn't work).
- [x] Tutorial verified working and up-to-date? Have we added `make user` and a guide on how to run the frontends?
  - `make_user` specified here, but I think the [admin ui](https://ethyca.github.io/fidesops/guides/users/) docs could be improved. (Catherine- I've requested the following be added to Elliot's PR- https://github.com/ethyca/fidesops/pull/364#issuecomment-1092147695)
- [x] Fidesdemo verified working and up-to-date? The versions are pinned but @NevilleS — have you noticed anything / what do you need here? (Verified by Catherine)
- [x] New/updated API endpoints described in the Guides? (Catherine- small copy changes here- https://github.com/ethyca/fidesops/pull/373)
- [x] New/updated API endpoints included in the Postman collections?
  - Hubspot, Segment, Mailchimp, Sentry examples in Postman (verified by Dawn) Stripe is not (we don't need every saas connector in postman, just useful to have a few examples) (Catherine- verified we also have new `user` and `login`/`logout` endpoints in postman)
- [x] New tables/columns added to database diagram?
  - Y: (Verified by Dawn) `privacy_request.reviewed_by`, `reviewed_at` columns added. Also `fidesopsuser` table was [added to the diagram](https://github.com/ethyca/fidesops/blob/main/docs/fidesops/docs/img/app_database.png). Client table had `fides_key` and `user_id` columns added too.
