### ISSUE TITLE
Fully replace `make` with `nox`

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fidesops#932]
### Is your feature request related to a specific problem?

When #919 gets merged, we'll have `nox` targets to fully replace the Makefile and should do so.

### Describe the solution you'd like

There will be a few steps here:

* [x]  Socialize the dev flow changes to the fidesops team (a short video should suffice going through some of the new usage patterns)
* [x]  updating the `docker-compose` file to match how `fidesctl` handles image building/usage (#966)
* [x]  Updating the docs where there is a reference to the Makefile (#960)
* [x]  The riskiest part, which is updating all of the CI workflows (#966)

**Comment by ThomasLaPiana** [comment]
looks like the docs updates are being done in #960
